theme: minima
title: This is going to be *awesome*
author: Nicole
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am awesome, so I'm here to offer my awesome advice.

# social links
twitter_username: N/A # DO NOT include the @ character, or else the build will fail!
github_username:  nicolenumrich # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
